generator: admingenerator.generator.propel
params:
  model: FOS\UserBundle\Propel\User
  namespace_prefix: Deuteron
  subfolder: Bundle
  bundle_name: UserBundle
  fields: ~

builders:
  list:
    params:
      title: List for Bundle\UserBundle
      display: [username, email]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [username, email]
  new:
    params:
      title: New object for Bundle\UserBundle
      display: ~
      actions:
        list: ~
  edit:
    params:
      title: You're editing the object "{{ User.username }}"
      display: ~
      actions:
        list: ~
  delete: ~
